# Generated by Django 5.2.4 on 2025-07-03 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('employee', '0001_initial')]

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('871a054e-a9ae-49b5-a2a8-0f959a45f1b9'), primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(default='John', verbose_name='Name')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='Age')),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='Department')),
            ],
        ),
    ]
