# Generated by Django 5.2.4 on 2025-07-03 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cf2f5424-d0d8-47dd-ba40-e82b40bc76d5'), primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
