# Generated by Django 5.2.4 on 2025-07-03 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_position_alter_department_createdat_and_more'),
        ('employee', '0002_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.position', verbose_name='职位名称'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(default=18, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='createdAt',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('85f89e98-a12a-46d1-9fc6-c44defb54bf9'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='John', verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
