# Generated by Django 5.2.4 on 2025-07-03 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_department_id_alter_position_id'),
        ('employee', '0003_employee_position_alter_employee_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ba4d12a3-55e3-4a33-9f08-b351410ac1e5'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.position', verbose_name='职位名称'),
        ),
    ]
