# Generated by Django 5.2.4 on 2025-07-03 13:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('261daee4-ae6c-4fc2-bced-99620644b024'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
