# Generated by Django 5.2.4 on 2025-07-03 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de154f81-e5dd-42c9-9141-8bdff02262c1'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
