# Generated by Django 5.2.4 on 2025-07-03 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_employee_name_alter_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updatedAt',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1df39335-735c-4385-a8a4-76b3e5493003'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
