# Generated by Django 5.2.4 on 2025-07-03 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_employee_createdat_remove_employee_updatedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='createdAt',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fcc6fb38-a258-4fea-abe8-4b91e2af4fee'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
