# Generated by Django 5.2.4 on 2025-07-09 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_employee_createdat_employee_updatedat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="编号",
            ),
        ),
    ]
