# Generated by Django 5.2.4 on 2025-07-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_department_alter_employee_id_and_more'),
        ('orgunit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgunit',
            name='leader',
        ),
        migrations.AddField(
            model_name='orgunit',
            name='leaders',
            field=models.ManyToManyField(blank=True, related_name='managed_units', to='employee.employee', verbose_name='管理人员'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='组织层级'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='type',
            field=models.CharField(max_length=50, verbose_name='类型'),
        ),
    ]
