# Generated by Django 5.2.4 on 2025-07-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgunit', '0002_remove_orgunit_leader_orgunit_leaders_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgunit',
            options={'verbose_name': '组织层级信息', 'verbose_name_plural': '组织层级信息'},
        ),
    ]
