# Generated by Django 5.2.4 on 2025-07-03 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9e473fdd-bf75-4de1-b809-da0c297bf5f6'), primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(verbose_name='Department Name')),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
