# Generated by Django 5.2.4 on 2025-07-03 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76a964e9-d7f4-47fc-8f31-0251d74237a1'), primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
