# Generated by Django 5.2.4 on 2025-07-03 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d108322f-6294-4107-89ed-bcc73ee72cc0'), primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(verbose_name='职位名称')),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='createdAt',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('813e56d7-54ab-4e7e-b702-27fe35cd7349'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
