# Generated by Django 5.2.4 on 2025-07-03 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_position_alter_department_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f58cd07e-6cca-4d9e-94aa-d53a96cc5e46'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b952efb7-8609-4745-a817-9d667e97c6d7'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
