# Generated by Django 5.2.4 on 2025-07-03 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_department_id_alter_position_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门信息', 'verbose_name_plural': '部门信息'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': '职位信息', 'verbose_name_plural': '职位信息'},
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4535556e-757b-4ab0-a490-b9622ad4756b'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ba4aeab5-7ad2-42b0-bbfc-08b4563c6b3d'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
