# Generated by Django 5.2.4 on 2025-07-03 13:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_department_options_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('35fe93c2-6b70-40f4-86dc-b3b2d6151d70'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('203d7536-4e95-4740-a6bb-32c4baca0abc'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
