# Generated by Django 5.2.4 on 2025-07-03 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_alter_department_id_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('89ab0ac0-bca8-4159-b289-e03cfcd4736a'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0c7f2963-f27d-4c9b-88b5-7db5a366ef3a'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
