# Generated by Django 5.2.4 on 2025-07-03 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_alter_department_id_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.UUID('952d7ea9-6193-4859-ae05-7ffece10b974'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4788dd89-75dd-4448-95a1-6100e7c1f386'), primary_key=True, serialize=False, verbose_name='编号'),
        ),
    ]
