# Generated by Django 5.2.4 on 2025-07-09 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0009_alter_department_id_alter_position_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("739515e3-e15d-4098-b43c-a519fdade5e5"),
                primary_key=True,
                serialize=False,
                verbose_name="编号",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("86884c2d-77ab-4904-9977-13ddbf94d806"),
                primary_key=True,
                serialize=False,
                verbose_name="编号",
            ),
        ),
    ]
