# Generated by Django 5.2.4 on 2025-07-09 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0010_alter_department_id_alter_position_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("bcad16f3-cd0e-4c05-98f4-e4a0eebd68fb"),
                primary_key=True,
                serialize=False,
                verbose_name="编号",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("69ec12b5-9956-42cc-8e42-9f117e4cece2"),
                primary_key=True,
                serialize=False,
                verbose_name="编号",
            ),
        ),
    ]
