# Generated by Django 5.2.4 on 2025-07-09 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0011_alter_department_id_alter_position_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("868a866d-40a7-4224-babd-f9f9e021c4de"),
                primary_key=True,
                serialize=False,
                verbose_name="编号",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("78c8d96f-2c6c-48fb-bd4c-9165e46bae5c"),
                primary_key=True,
                serialize=False,
                verbose_name="编号",
            ),
        ),
    ]
